### ISSUE TITLE
If browser isnt Chrome/Safari, add a popup saying it's not supported.

### ISSUE THREAD

**Issue by LazarValkov** [ICMLRecommender/frontend#27]

**Comment by LazarValkov** [comment]
Make sure this popup isn't shown on Safari.

**Comment by LazarValkov** [comment]
need to also test it on IE

**Comment by lcharlin** [comment]
I'm using the app on my iphone with the latest iOS and the newest chrome. And with both Safari and Chrome I get the pop up saying that the browsers are not supported.

Here are the user-agent's string those browsers send:
Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_3 like Mac OS X) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.0 Mobile/14G60 Safari/602.1

Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_3 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) CriOS/60.0.3112.72 Mobile/14G60 Safari/602.1

**Comment by LazarValkov** [comment]
addressed in c406f4c7645a86a3ab0a5ef93ca91e3b2d7819f7 by Taimur
