### ISSUE TITLE
Make `paper-dialog` popups appear full-screen on mobile

### ISSUE THREAD

**Issue by refrigerator** [ICMLRecommender/frontend#32]
### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by LazarValkov** [comment]
see iron-media-query (should help detect the device size)

**Comment by refrigerator** [comment]
done
