### ISSUE TITLE
Schedule improvements: keynotes, posters

### ISSUE THREAD

**Issue by ywteh** [ICMLRecommender/frontend#35]
Would be nice for keynotes and test of time to be their own sessions.

Specific suggestions:
- Label the 7:00 to be 9:00 as that's the real start of the day (you can keep registration and early morning coffee break).
- Create a 17:15 session for the keynotes then.
- If there is space, create a 18:30 poster session, and list all papers being presented there (bookmarked/liked first, and alphabetically otherwise).

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by LazarValkov** [comment]
@ywteh  , I assume that by "sessions" you mean timeslots? I think these are good suggestions, will try to implement.

**Comment by ywteh** [comment]
Yes.  Thanks.  for posters: if can list the recommended ones too earlier, would be great.

**Comment by LazarValkov** [comment]
Update: I've made most of the changes, except for ordering the posters. Would you mind looking at how timeslots are arranged at the moment and sharing if you agree? Also, I wonder how important the ordering is? Since the poster count is 140, the popup opens slowly on my PC, will need to test it on mobile, but if it's already sluggish -well, we might be able to optimise the code, but I'm not sure if it's worth the time?

**Comment by ywteh** [comment]
Schedule looks fine with me.  Maybe others have other opinions.

Colours: It would be good for Invited and Test of Time talks to be giving the same colour that is distinct and more eye-catching than currently.

Poster ordering: I do think having the liked, bookmarked, and recommended papers first would be useful.  Ordering of the rest: I don't know.  It is hard to find, and I don't understand what ordering it is currently.  I think maybe order by sessions that the papers appear in?

Speed: It is fine for me on the train.

**Comment by adrtod** [comment]
Regarding colours, Test of Time will be of type "Award" instead of talk (see #34)

**Comment by LazarValkov** [comment]
Colors added. Also, ordering posters by bookmarked/liked atm. Recommended is possible, if time permits.

**Comment by adrtod** [comment]
Ordering posters by sessions that the papers appear in is possible thanks to the `session_topic` field of each paper
