### ISSUE TITLE
Browser incompatibility complaint

### ISSUE THREAD

**Issue by ywteh** [ICMLRecommender/frontend#36]
It's complaining that my safari is not newest version. Same goes with chrome.

My iphone SE is updated.

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by ywteh** [comment]
it's an iphone SE

**Comment by refrigerator** [comment]
done
