### ISSUE TITLE
register view404

### ISSUE THREAD

**Issue by ywteh** [ICMLRecommender/frontend#38]
tapping on 'register' brings to 'View404' page.  This is safari on iphone SE.

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by refrigerator** [comment]
@ywteh I can't seem to recreate this - is the problem still happening for you? Could you try clearing cache and seeing if that works? thanks

**Comment by ywteh** [comment]
Seems to work for me now.  Not sure why it didn't work before.  cheers.
