### ISSUE TITLE
password reset email rewording

### ISSUE THREAD

**Issue by ywteh** [ICMLRecommender/frontend#39]
It says my username already exists.  So I requested password reset, and got the email.   The email is a bit confusing.  Maybe say: Please use this secret key to reset your password at the 'Reset password' page?  If possible provide a URL link.  Also, flip the form so that secret key is above new password.

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by LazarValkov** [comment]
@hptruong93 , can you make the necessary changes? If you add a url with parameters 
https://icml.papro.org.uk/reset?username=username&secret=secret  (URI encoded, of course),
I can detect these parameters and fill in the form.

**Comment by hptruong93** [comment]
@LazarValkov 
1) You should redirect people to the password reset page.
2) I added the link with 30a921566739f216db72311d5e7b5e96837dc4c6.
