### ISSUE TITLE
ordering sessions

### ISSUE THREAD

**Issue by ywteh** [ICMLRecommender/frontend#40]
If possible, please follow the session ordering on the google sheet schedule, because it's ordered from largest room to smallest (so is good proxy for most popular to least).

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by LazarValkov** [comment]
I think the easiest way might be to have an array of the rooms in increasing order, which I can use in a custom comparator in the script. @adrtod , from your observation of the data, do you know how many numbers there are and how easy it would be to obtain such an array? 

edit: is it the following (the higher, the bigger)
Darling Harbour Theatre
Parkside 1
Parkside 2
C4.5
C4.9& C4.10
C4.1
C4.4
C4.8
C4.6 & C4.7

**Comment by adrtod** [comment]
Exactly.
Do you need me to produce something @LazarValkov ?

**Comment by LazarValkov** [comment]
@adrtod  no, I think that's fine, thanks for confirming
