### ISSUE TITLE
showing liked papers in library

### ISSUE THREAD

**Issue by ywteh** [ICMLRecommender/frontend#42]
There's a library which shows all bookmarked papers.  Can we also see the liked papers in the library too?

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by refrigerator** [comment]
done
