### ISSUE TITLE
"ICML 2017 Team" renaming

### ISSUE THREAD

**Issue by ywteh** [ICMLRecommender/frontend#43]
Hi, for correctness, it might be better to refer to ourselves as ICML 2017 Recommender App Team, instead of ICML 2017 Team.  Generally, it's good to make sure that we don't refer ourselves in any way as the organization behind ICML until we get the ok of the IMLS Board.  Unfortunately this is probably too late to do this year.

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by LazarValkov** [comment]
@hptruong93  , I think this refers to the email sent out for password recovery?

**Comment by hptruong93** [comment]
Should be fixed with 0810e785b346239539ef1ee36a127c282293b6bf and c6b4b66705ab77623c167ed116e0cfd68ef184c6

**Comment by LazarValkov** [comment]
Front-end should be fixed as well.
