### ISSUE TITLE
Paper details view problem on Safari 10

### ISSUE THREAD

**Issue by ywteh** [ICMLRecommender/frontend#46]
This is Safari 10 on Mac laptop.

Bookmarks, likes, and comments not showing up in paper details view.  The topics, are always showing up as "Stats, ML", and session as "Sat 2pm, Room 12".  No comments show up.

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by refrigerator** [comment]
@ywteh Works for me on Safari 10 on mac - have you tried clearing your cache and saved data?

**Comment by ywteh** [comment]
youre right. thx.
