### ISSUE TITLE
Keynote talk information missing

### ISSUE THREAD

**Issue by ywteh** [ICMLRecommender/frontend#47]
We should include speaker, bio, and abstract.

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by adrtod** [comment]
I have added that in the content field of Invited Talks in the schedule db

**Comment by adrtod** [comment]
@LazarValkov can you display it?

**Comment by adrtod** [comment]
Authors bio are in the authors db

**Comment by LazarValkov** [comment]
@adrtod  How do you imagine this information being displayed?

**Comment by adrtod** [comment]
This can be displayed like a paper view with both abstract and bio
