### ISSUE TITLE
Paper shows up twice in library

### ISSUE THREAD

**Issue by ywteh** [ICMLRecommender/frontend#54]
Papers both bookmarked and liked shows up twice in library.

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by LazarValkov** [comment]
Closing this issue, since it's a copy of #51
