### ISSUE TITLE
author names do not appear when clicking on paper

### ISSUE THREAD

**Issue by lcharlin** [ICMLRecommender/frontend#58]
### Description

The name of authors does not appear on the "paper view"

I think this is problematic since names are often cut off from the "session view"

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by LazarValkov** [comment]
should be already solved, it's just that the newest version isn't yet deployed.
