### ISSUE TITLE
the like button doesn't always turn on.

### ISSUE THREAD

**Issue by lcharlin** [ICMLRecommender/frontend#59]
### Description

I don't have a MWE for this one but I've noticed (on three independent occasions) that after browsing papers with the app for a bit one cannot like papers anymore. That is, after clicking on the like button the heart will turn green for a second but will then go back to gray. The bookmark button does not seem to have this problem. 

I'm happy to investigate further if needed.
### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by LazarValkov** [comment]
Could you provide steps to reproduce?

**Comment by refrigerator** [comment]
hey laurent, could you have the browser console open and see if it says anything when this happens? 

the like button has an "optimistic" timeout where the frontend assumes for 2 seconds that the 'like' has successfully gone through in the server + database so that it feels to the user that it's instant. so if it then goes grey it suggests that the server doesn't like it and it hopefully gives us a useful error in the browser console

**Comment by lcharlin** [comment]
This is on my mobile and I don't think there is a console.

I can try to reproduce from my computer. I'll let you know. 

Laurent

**Comment by lcharlin** [comment]
Here's the desktop output. I confirm that in this case the bookmark button still worked. 

Let met know if you need anything else.

<img width="1256" alt="screen shot 2017-08-04 at 10 39 27 am" src="https://user-images.githubusercontent.com/1480264/28973473-5128d93a-7901-11e7-9a68-f14758a9f5d5.png">

**Comment by lcharlin** [comment]
One small thing, the problem is the same with un-liking. Screenshot below.
<img width="1274" alt="screen shot 2017-08-04 at 10 41 56 am" src="https://user-images.githubusercontent.com/1480264/28973572-9dd22a48-7901-11e7-9973-133ac5971ffd.png">

**Comment by refrigerator** [comment]
thanks laurent, will investigate further.

**Comment by refrigerator** [comment]
tried very hard to recreate this but still unable, so not much I can do right now - I suggest we see if any of the beta testers encounter it in the next couple of days and revisit if so
