### ISSUE TITLE
Registering username beginning with a number is not allowed, but currently presents exception

### ISSUE THREAD

**Issue by LazarValkov** [ICMLRecommender/frontend#60]

**Comment by LazarValkov** [comment]
@hptruong93 , I'm handling it on the front end atm, but it'd be good to also implement a check on the backend.

**Comment by hptruong93** [comment]
Fix with the following commit
https://github.com/ICMLRecommender/backend/commit/def36c81f4311f090eb9d42df67292f90e6633fd
