### ISSUE TITLE
Search bar not working

### ISSUE THREAD

**Issue by adrtod** [ICMLRecommender/frontend#64]
I think this bar should be searching in all the papers of the conference.

**Comment by LazarValkov** [comment]
How did you figure they don't?

**Comment by adrtod** [comment]
Sorry it was probably due to my browser. Cannot reproduce it

**Comment by adrtod** [comment]
Found it :) It is actually case sensitive. Can it be case insensitive?

**Comment by LazarValkov** [comment]
fixed with c3e6bc45f47d8e362c569eaa58ac4b48ae4e8cf8
