### ISSUE TITLE
layout in list view

### ISSUE THREAD

**Issue by ywteh** [ICMLRecommender/frontend#68]
After an item with "bookmark", subsequent items are shifted lower.  

Safari 10 Mac OS.
![untitled](https://user-images.githubusercontent.com/173690/28946416-4274fe10-78dd-11e7-8e3f-2c241adc8ba9.jpeg)

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by refrigerator** [comment]
edit: looks like lazar has fixed this now
