### ISSUE TITLE
dismissing recommemdations

### ISSUE THREAD

**Issue by LazarValkov** [ICMLRecommender/frontend#71]
### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by adrtod** [comment]
Dismissed papers reappear after a refresh

**Comment by LazarValkov** [comment]
@adrtod  

can you keep the following <userdb>/recommendations fields:   dismissed, dismissedTrending
