### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by lcharlin** [ICMLRecommender/frontend#72]
### Description

Note: This app is in pre-release mode for ICML 2017. Please send feedback
and bug reports to icml17app@gmail.com or file an issue on our github project page
(https://github.com/ICMLRecommender/frontend/issues).

What is this app?

This app helps navigate the rich program of ICML 2017.  The app enables
users to quickly find interesting papers, publicly comment them, register
their interest using 'like' and 'bookmark', and browse what others are
interested in. In addition, users' preferences feed a personalized paper
recommendation engine.

The recommendation engine is based on the collaborative topic regression
(CTR) model of C. Wang and D. Blei.

CTR:
http://www.cs.columbia.edu/~blei/papers/WangBlei2011.pdf

Bookmarks and Likes.

Papers you choose to bookmark or like are made available through your
"Library" page. 

The difference between bookmarks and likes is that liked papers are fed
into the recommendation engine.

Recommendations.

Recommendations are available through the "Feed" page and are updated
every two minutes. On that page recommended papers are preceded by
trending papers which shows some of the most popular papers.

Who built it?

The app was designed and built by a team of machine learning students and
researchers spread across England, France, and Canada.

Adrien Todeschini, [Scorelab.io](http://Scorelab.io)
Hoai Phuoc Truong, McGill University
James Ravenscroft, University of Warwick
Laurent Charlin, Université de Montréal (HEC)
Lazar Valkov, University of Edinburgh
Maria Liakata, University of Warwick
Taimur Abdaal, Oxford University
Valerio Perrone, University of Warwick & Oxford University
Yee Whye Teh, Oxford University

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by adrtod** [comment]
From @ywteh on slack:

Btw, might be good to describe a bit out goals - to develop something usable by community, both as test bed for recommender apps and for people to find good papers. Say something about data being used?

**Comment by lcharlin** [comment]
**Note:** This app is in pre-release mode for ICML 2017. Please send feedback
and bug reports to icml17app@gmail.com or file an issue on our [github project page](https://github.com/ICMLRecommender/frontend/issues).


**What is this app?**
This app helps navigate the rich program of ICML 2017. The app provides an easily
navigable schedule, enables users to quickly find interesting papers, publicly 
comment them, register their interest using 'like' and 'bookmark', and browse what 
others are interested in. In addition, users' preferences feed a personalized paper
recommendation engine.



**Bookmarks and Likes.**
Papers you choose to bookmark or like are made available through your
"Library" page.

The difference between bookmarks and likes is that liked papers are fed
into the recommendation engine.


**Recommendations.**
Recommendations are available through the "Feed" page and are updated
every two minutes. On that page recommended papers are preceded by
trending papers which shows some of the most popular papers.

The recommendation engine is based on the [collaborative topic regression (CTR)](http://www.cs.columbia.edu/~blei/papers/WangBlei2011.pdf) model of C. Wang and D. Blei. We also used a few tricks to integrate the model with our app. 
 

**Why are we building it?**
There are a few reasons one of which is that it can be challenging to keep up with all of the great work published at conferences. We believe that an easy to use app and a good recommendation engine can help surface interesting papers.

Moreover, we built this app as a service to the community, we will open source the app. We would like others to use and even build on it. We believe that the app can also be used as a test bed for recommender engines. As such the app keeps detailed (and anonymous) logs for future offline analysis and model comparisons.


**Who is involved?**
The app was designed and built by a team of machine learning students and
researchers spread across England, France, and Canada.

**Adrien Todeschini**, Scorelab.io
**Hoai Phuoc Truong**, McGill University
**James Ravenscroft**, University of Warwick
**Laurent Charlin**, Université de Montréal (HEC)
**Lazar Valkov**, University of Edinburgh
**Maria Liakata**, University of Warwick, Alan Turing Institute
**Taimur Abdaal**, University of Oxford
**Valerio Perrone**, University of Warwick
**Yee Whye Teh**, University of Oxford, DeepMind, Alan Turing Institute

**Comment by hptruong93** [comment]
Once we've finalized this, I think we should put it as part of this project's README. (Let me know I can add it to the existing README file).

**Comment by lcharlin** [comment]
Good idea!

**Comment by ywteh** [comment]
looks great, I edited it a bit, to mention the schedule and update affiliations.
