### ISSUE TITLE
Topics not showing up during registration

### ISSUE THREAD

**Issue by ywteh** [ICMLRecommender/frontend#77]
On Safari Mac OS.
<img width="461" alt="notopics" src="https://user-images.githubusercontent.com/173690/29002881-d35d045e-7aef-11e7-8ef8-9e435f7f1fbf.png">

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by adrtod** [comment]
Neither on Chrome Android...
But ok on Chrome Ubuntu
